#! /bin/sh

get_group_by_id()
{
   local gid="$1"

   getent group | sed -n -e "/:${gid}:"'/s/^\([A-Za-z0-9_-]*\).*/\1/p'
}

imagename="${1:-yo-code}"

# https://stackoverflow.com/questions/4598001/how-do-you-find-the-original-user-through-multiple-sudo-and-su-commands
me="`logname`"
userid="`id -u "${me}" `"
groupid="`id -g "${me}" `"
groupname="`get_group_by_id "${groupid}"`"


[ -z "${groupname}" ] && echo "Couldn't figure out groupname, will use docker" >&2

if docker build -f Dockerfile \
             --build-arg "USERNAME=${me}"  \
             --build-arg "USERID=${userid}" \
             --build-arg "GROUPID=${groupid}" \
             --build-arg "GROUPNAME=${groupname}" \
             -t "${imagename}" \
             "$@" \
             .
then
   >&2 echo ""
   >&2 echo "Add the following command to your bashrc"
   >&2 echo ""
   echo "   alias yo='sudo docker run -i -t -v \"\${PWD}:/mnt/host\" ${imagename} --no-insight'"
fi

