#!/bin/sh

[ "${TRACE}" = 'YES' -o "${MULLE_JEKYLL_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


case " $* " in
   *\ serve\ *)
      if [ -f _config.yml ]
      then
         url="`sed -n 's/^baseurl:[ "]*\([^" ]*\).*/\1/p' _config.yml`"
         sedcommand="s|http://0.0.0.0:4000${url}/|http://127.0.0.1${url}/index.html|"
      fi
   ;;
esac

# can also run bundle or bundler I suppose with this, if you symlink to
# this script

cmd="`basename -- "$0" `"

MULLE_DOCKERNAME="jekyll" \
MULLE_DOCKERIZE_MOUNT_POINT="/srv/jekyll" \
DOCKERRUNFLAGS="-i -t --rm --publish 127.0.0.1:80:4000/tcp" \
   mulle-dockerize "${cmd}" "$@" | sed -e "${sedcommand}"